// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const buildDatabaseUrl = (): string | undefined => {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  const rawDbUrl = process.env["DB_URL"];
  const user = process.env["DB_USERNAME"];
  const password = process.env["DB_PASSWORD"];
  if (!rawDbUrl || !user || !password) {
    return undefined;
  }

  const normalized = rawDbUrl.replace(/^jdbc:/, "");
  const parsed = new URL(normalized);
  parsed.username = user;
  parsed.password = password;
  if (!parsed.searchParams.has("schema")) {
    parsed.searchParams.set("schema", "public");
  }
  return parsed.toString();
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: buildDatabaseUrl(),
  },
});
